### PR TITLE
docs: fix broken "rate limiting" link

### PR DESCRIPTION
**Pull request by cwaldren-ld**
Updates dead link in README.

### CODE REVIEW

**Comment by cwaldren-ld** [comment]
I don't know how our [generated docs](https://apidocs.launchdarkly.com/#section/Overview/Rate-limiting) work - do those come from this repo? The link works there, but not on the Github README.

Perhaps merging this would then break the generated docs?

**Review by lucywyman — CHANGES_REQUESTED** [review]
Oh this is actually generated from this doc I believe: https://github.com/launchdarkly/gonfalon/blob/main/apidocs/content/overview.md?plain=1#L243 Can you update it there?

**Comment by lucywyman** [comment]
> I don't know how our [generated docs](https://apidocs.launchdarkly.com/#section/Overview/Rate-limiting) work - do those come from this repo? The link works there, but not on the Github README.
> 
> Perhaps merging this would then break the generated docs?

Oh dang, I thought that this would still work for the generated docs but [it does not](https://apidocs.launchdarkly.com/#rate-limiting) :( Hmm....

**Comment by cwaldren-ld** [comment]
Another idea: we could just delete the link, since the linked section is like 1 inch below the table. Unsatisfying though.

**Review by sunnyguduru — APPROVED** [review]

**Pull request closed without merging**
